export const SEGMENTS = {
  ID: '/:id',
  APP: '/app',
  COURSE: '/course',
  INSTRUCTOR: '/instructor',
  PLAYER: '/player',
  UPLOAD: '/upload',
} as const;

export const PATHS = {
  APP: SEGMENTS.APP,
  APP_COURSE_ID: `${SEGMENTS.APP}${SEGMENTS.COURSE}${SEGMENTS.ID}`,
  APP_COURSE_ID_PLAYER: `${SEGMENTS.APP}${SEGMENTS.COURSE}${SEGMENTS.ID}${SEGMENTS.PLAYER}`,
  APP_INSTRUCTOR_UPLOAD: `${SEGMENTS.APP}${SEGMENTS.INSTRUCTOR}${SEGMENTS.UPLOAD}`,
} as const;
